export default function AIAnalysis({ text }) {
  return (
    <section className="rounded-lg border border-signal/30 bg-signal/[0.04] p-6">
      <div className="flex items-center gap-2">
        <svg
          width="16"
          height="16"
          viewBox="0 0 24 24"
          fill="none"
          stroke="#4FD1C5"
          strokeWidth="1.8"
        >
          <path d="M12 3v3M12 18v3M4.2 4.2l2.1 2.1M17.7 17.7l2.1 2.1M3 12h3M18 12h3M4.2 19.8l2.1-2.1M17.7 6.3l2.1-2.1" />
          <circle cx="12" cy="12" r="3.5" />
        </svg>
        <h2 className="text-sm font-medium uppercase tracking-wide text-signal">
          AI-Assisted Interpretation
        </h2>
      </div>

      <p className="mt-4 whitespace-pre-line text-sm leading-relaxed text-ink-muted">
        {text}
      </p>

      <p className="mt-4 border-t border-signal/20 pt-3 text-xs text-ink-faint">
        This explanation is generated by an AI model interpreting the
        scanner's structured evidence. It is not proof of a vulnerability —
        confirm findings manually against the lab application before drawing
        conclusions.
      </p>
    </section>
  );
}
